name: api_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.3
  titled_navigation_bar: ^5.0.0-nullsafety.0
  cached_network_image: ^3.1.0
  shared_preferences: null
  flutter_svg: ^0.20.0-nullsafety.3
  google_fonts: ^2.1.0
  flutter_native_splash: null
  flutter_launcher_icons: null

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter_icons:
  image_path: "assets/spalsh_screen_icon.png"
  android: "launcher_icon"
  ios: true

flutter_native_splash:
  color: "#32b3a4"
  image: assets/splash.png
  color_dark: "#32b3a4"
  image_dark: assets/splash.png
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill
  flutter_svg: null

flutter:

  uses-material-design: true


  assets:
    - images/

  fonts:
     - family: Noticia Text
       fonts:
         - asset: assets/fonts/NoticiaText-Bold.ttf
         - asset: assets/fonts/NoticiaText-BoldItalic.ttf
         - asset: assets/fonts/NoticiaText-Italic.ttf
         - asset: assets/fonts/NoticiaText-Regular.ttf
           weight: 700

     - family: Neuton
       fonts:
         - asset: assets/fonts/Neuton-Bold.ttf
         - asset: assets/fonts/Neuton-ExtraBold.ttf
